# Generated by Django 4.2.2 on 2023-11-20 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_mat',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_pat',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero_calle',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('administrador', 'Administrador'), ('tecnico', 'Técnico')], default='usuario', max_length=50),
        ),
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_pat', models.CharField(max_length=255)),
                ('apellido_mat', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('numero_calle', models.IntegerField(default=0, null=True)),
                ('colonia', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('cp', models.IntegerField(default=0, null=True)),
                ('telefono', models.IntegerField(default=0, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
