# Generated by Django 4.2.2 on 2023-10-08 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mantenimientoSLOGIN', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='administradores', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('tecnico', 'Técnico')], default='administrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='administradores', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='datosadministrador',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('tecnico', 'Técnico')], default='usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='datostecnicos',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('tecnico', 'Técnico')], default='tecnico', max_length=20),
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('tecnico', 'Técnico')], default='tecnico', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, related_name='tecnicos', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='tecnicos', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
