# Generated by Django 4.2.2 on 2023-11-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0002_remove_usuario_apellido_mat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('superusuario', 'Superusuario'), ('administrador', 'Administrador'), ('tecnico', 'Técnico')], default='Administrador', max_length=50),
        ),
    ]
