# Generated by Django 4.2.2 on 2023-10-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0002_remove_administrador_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
