# Generated by Django 4.2.2 on 2023-09-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0002_operadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadores',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='operadores/'),
        ),
    ]
