# Generated by Django 4.2.2 on 2023-10-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0003_administrador_is_staff_tecnico_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
