# Generated by Django 4.2.2 on 2023-09-25 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mantenimientoSLOGIN.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimientoSLOGIN', '0003_operadores_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero_calle', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Operadores',
        ),
    ]
