# Generated by Django 4.2.2 on 2023-11-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0003_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='cp',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='numero_calle',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='telefono',
            field=models.IntegerField(default='', null=True),
        ),
    ]
