# Generated by Django 4.2.2 on 2023-11-20 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0004_alter_datosusuario_cp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='cp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='numero_calle',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='telefono',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
