# Generated by Django 4.2.2 on 2023-10-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0004_alter_administrador_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
