# Generated by Django 4.2.2 on 2023-10-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0005_datostecnicos_datosusuario_foto_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datostecnicos',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('tecnico', 'Técnico')], default='tecnico', max_length=20),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='foto_user',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('tecnico', 'Técnico')], default='usuario', max_length=20),
        ),
    ]
