# Generated by Django 4.2.2 on 2023-11-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0005_alter_datosusuario_cp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosusuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
