# Generated by Django 4.2.2 on 2023-11-21 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0007_alter_datosusuario_cp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='apellido_mat',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='apellido_pat',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='calle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='ciudad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='colonia',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
