# Generated by Django 4.2.2 on 2023-11-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoSLOGIN', '0009_alter_datosusuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='cp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='numero_calle',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='telefono',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
