# Generated by Django 4.2.2 on 2023-08-18 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mantenimientoReportes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_maquina', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_parte', models.CharField(blank=True, max_length=100, null=True)),
                ('piezas', models.IntegerField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('horas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_reemplazo', models.DateField(blank=True, null=True)),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=mantenimientoReportes.models.maquina_image_path)),
                ('foto_filtro', models.ImageField(blank=True, null=True, upload_to=mantenimientoReportes.models.filtro_image_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
