# Generated by Django 4.2.2 on 2023-07-31 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mantenimientoReportes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_maquina', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('numero_parte', models.CharField(max_length=100)),
                ('piezas', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_reemplazo', models.DateField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=mantenimientoReportes.models.reporte_image_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
