# Generated by Django 4.2.2 on 2023-11-29 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimientoReportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='cantidad_piezas',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='costo_total',
        ),
        migrations.CreateModel(
            name='InventarioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_piezas', models.PositiveIntegerField(default=0)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.maquina')),
                ('partes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.catalogopartes')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_piezas', models.PositiveIntegerField(default=0)),
                ('Inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.inventario')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.maquina')),
                ('partes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.catalogopartes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
