# Generated by Django 4.2.2 on 2023-08-21 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimientoReportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_modificacion', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_maquina_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_anterior', models.TextField(blank=True, null=True)),
                ('numero_parte_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('piezas_anterior', models.IntegerField(blank=True, null=True)),
                ('costo_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('horas_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_reemplazo_anterior', models.DateField(blank=True, null=True)),
                ('qr_anterior', models.ImageField(blank=True, null=True, upload_to='qr/historial')),
                ('foto_anterior', models.ImageField(blank=True, null=True, upload_to='maquina_img/historial')),
                ('foto_filtro_anterior', models.ImageField(blank=True, null=True, upload_to='filtro_img/historial')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.reportes')),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
