# Generated by Django 4.2.2 on 2023-08-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
