# Generated by Django 4.2.2 on 2023-11-29 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0002_remove_inventario_cantidad_piezas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariostock',
            name='inventario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.inventario'),
            preserve_default=False,
        ),
    ]
