# Generated by Django 4.2.2 on 2023-08-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0002_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='foto_filtro_anterior',
            field=models.ImageField(blank=True, null=True, upload_to='filtros_img/historial'),
        ),
    ]
