# Generated by Django 4.2.2 on 2023-11-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogopartes',
            name='maquina',
        ),
        migrations.AddField(
            model_name='catalogopartes',
            name='maquinas',
            field=models.ManyToManyField(related_name='partes', to='mantenimientoReportes.maquina'),
        ),
    ]
