# Generated by Django 4.2.2 on 2023-08-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0002_alter_reportes_costo_alter_reportes_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='fecha_reemplazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='numero_parte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='piezas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
