# Generated by Django 4.2.2 on 2023-12-03 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientopartes',
            name='partes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.catalogopartes'),
        ),
    ]
