# Generated by Django 4.2.2 on 2023-12-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0003_alter_mantenimientopartes_partes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
