# Generated by Django 4.2.2 on 2023-08-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0003_alter_historial_foto_filtro_anterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='foto_anterior',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='foto_filtro_anterior',
        ),
    ]
