# Generated by Django 4.2.2 on 2023-11-29 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0003_inventariostock_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariostock',
            name='inventario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_stock', to='mantenimientoReportes.inventario'),
        ),
        migrations.DeleteModel(
            name='Inventario_Stock',
        ),
    ]
