# Generated by Django 4.2.2 on 2023-11-28 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0003_remove_inventario_mantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_entrada',
        ),
        migrations.AddField(
            model_name='inventario',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_piezas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.maquina'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='partes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.catalogopartes'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='piezas_entrada',
            field=models.PositiveIntegerField(),
        ),
    ]
