# Generated by Django 4.2.2 on 2023-11-29 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0004_alter_inventariostock_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='inventario_stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='mantenimientoReportes.inventariostock'),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='inventario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_stock', to='mantenimientoReportes.inventario'),
        ),
    ]
