# Generated by Django 4.2.2 on 2023-12-04 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0004_alter_inventario_fecha_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_mantenimiento', to='mantenimientoReportes.mantenimientopartes'),
        ),
        migrations.AlterField(
            model_name='mantenimientopartes',
            name='fecha_mantenimiento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='mantenimientopartes',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='mantenimientopartes',
            name='maquina',
        ),
        migrations.RemoveField(
            model_name='mantenimientopartes',
            name='partes',
        ),
        migrations.AddField(
            model_name='mantenimientopartes',
            name='inventario',
            field=models.ManyToManyField(blank=True, null=True, related_name='mantenimiento_inventario', to='mantenimientoReportes.inventario'),
        ),
        migrations.AddField(
            model_name='mantenimientopartes',
            name='maquina',
            field=models.ManyToManyField(related_name='mantenimientos', to='mantenimientoReportes.maquina'),
        ),
        migrations.AddField(
            model_name='mantenimientopartes',
            name='partes',
            field=models.ManyToManyField(to='mantenimientoReportes.catalogopartes'),
        ),
    ]
