# Generated by Django 4.2.2 on 2023-10-29 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimientoReportes', '0004_remove_historial_foto_anterior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maquina', models.TextField(max_length=100)),
                ('marca', models.TextField(max_length=100)),
                ('modelo', models.TextField(max_length=100)),
                ('foto_maquina', models.ImageField(blank=True, null=True, upload_to='maquinas/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
