# Generated by Django 4.2.2 on 2023-11-03 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimientoReportes', '0005_maquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pieza', models.TextField(max_length=100)),
                ('numero_pieza', models.TextField(max_length=20)),
                ('ultimo_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultimo_costo1', models.TextField(max_length=100)),
                ('horas_uso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_pieza', models.ImageField(blank=True, null=True, upload_to='partes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
