# Generated by Django 4.2.2 on 2023-12-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0005_alter_inventario_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientopartes',
            name='inventario',
            field=models.ManyToManyField(related_name='mantenimiento_inventario', to='mantenimientoReportes.inventario'),
        ),
    ]
