# Generated by Django 4.2.2 on 2023-11-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0006_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='ultimo_costo1',
        ),
    ]
