# Generated by Django 4.2.2 on 2023-12-06 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimientoReportes', '0006_alter_mantenimientopartes_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piezas_entrada', models.PositiveIntegerField()),
                ('piezas_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_piezas', models.IntegerField(default=0)),
                ('new_horas_maquina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movimiento', models.BooleanField(default=True)),
                ('maquinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.maquina')),
                ('partes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientoReportes.catalogopartes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='mantenimientopartes',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='mantenimientopartes',
            name='maquina',
        ),
        migrations.RemoveField(
            model_name='mantenimientopartes',
            name='partes',
        ),
        migrations.RemoveField(
            model_name='mantenimientopartes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='MantenimientoPartes',
        ),
    ]
