# Generated by Django 4.2.2 on 2023-11-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0006_remove_inventario_maquina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='inventario_stock',
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad_piezas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='InventarioStock',
        ),
    ]
