# Generated by Django 4.2.2 on 2023-11-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0007_remove_inventario_ultimo_costo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidad_pieza',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
