# Generated by Django 4.2.2 on 2023-11-08 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimientoReportes', '0008_inventario_cantidad_pieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='contador_horas',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='foto_pieza',
            field=models.ImageField(blank=True, null=True, upload_to='inventario/'),
        ),
        migrations.CreateModel(
            name='Partes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_partes', models.TextField(max_length=100)),
                ('numero_partes', models.TextField(max_length=20)),
                ('cantidad_partes', models.IntegerField()),
                ('ultimo_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_uso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_restantes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_partes', models.ImageField(blank=True, null=True, upload_to='partes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
