# Generated by Django 4.2.2 on 2023-12-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0008_alter_movimientoinventario_maquinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='new_horas_maquina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
