# Generated by Django 4.2.2 on 2023-12-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0009_alter_movimientoinventario_new_horas_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='piezas_entrada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
