# Generated by Django 4.2.2 on 2023-11-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0009_maquina_contador_horas_alter_inventario_foto_pieza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partes',
            name='inventarios',
            field=models.ManyToManyField(related_name='partes', to='mantenimientoReportes.inventario'),
        ),
        migrations.AddField(
            model_name='partes',
            name='maquinas',
            field=models.ManyToManyField(related_name='partes', to='mantenimientoReportes.maquina'),
        ),
    ]
