# Generated by Django 4.2.2 on 2023-11-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0012_remove_partes_horas_restantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='cantidad_pieza',
            new_name='cantidad_partes',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='ultimo_costo',
            new_name='costo_aproximado',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='nombre_pieza',
            new_name='nombre_partes',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='numero_pieza',
            new_name='numero_partes',
        ),
        migrations.RenameField(
            model_name='partes',
            old_name='ultimo_costo',
            new_name='costo_aproximado',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='foto_pieza',
        ),
        migrations.AddField(
            model_name='inventario',
            name='foto_partes',
            field=models.ImageField(blank=True, null=True, upload_to='partes/'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='inventarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='mantenimientoReportes.inventario'),
        ),
    ]
