# Generated by Django 4.2.2 on 2023-11-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0013_rename_cantidad_pieza_inventario_cantidad_partes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_partes',
            field=models.IntegerField(default=0),
        ),
    ]
