# Generated by Django 4.2.2 on 2023-11-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0014_alter_inventario_cantidad_partes'),
    ]

    operations = [
        migrations.AddField(
            model_name='partes',
            name='maquina_relacionada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
