# Generated by Django 4.2.2 on 2023-11-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoReportes', '0016_alter_inventario_foto_partes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partes',
            name='maquina_relacionada',
        ),
    ]
